### PR TITLE
Documented chess Eval centereval with comments

### LINKED ISSUE #605: Document Chess\Eval\CenterEval with comments
Document [Chess\Eval\CenterEval](https://github.com/chesslablab/php-chess/blob/main/src/Eval/CenterEval.php) with comments to briefly explain the purpose of each part. Remember to write a brief description of the heuristic along with an explanation of how it has been implemented.

### PR DESCRIPTION
**Pull request by Neel-07**
Closes #605

### CODE REVIEW

**Review by programarivm — CHANGES_REQUESTED** [review]
One step at a time, you're almost there! Issues must be solved one by one. This particular one only requires changing one file. Thus, the changes to the `src/Eval/DefenseEval.php` file are to be reverted.

**Comment by Neel-07** [comment]
@programarivm i didnt pull the recent changes  then push the centerEval ( updated ) into the pr and there were some merge conflicts in defenseeval so solved those, that is the reason the defenseeval file has changes, will the revert back the changes made in defenseeval.

**Comment by programarivm** [comment]
Thanks for contributing to this repo!

Let me point out the following:

- The heuristic has been described thoroughly.
- The coding convention is now the same used in `src/Eval/CheckabilityEval.php` and `src/Eval/DefenseEval.php`

Keep it up,

**Review by programarivm — APPROVED** [review]
The heuristic has been described thoroughly.

**Pull request merged**
