### PR TITLE
Generalize the Engine class to make it work with any type of UCI engine.

### PR DESCRIPTION
**Pull request by Disservin**
I'll open this as a draft for now, because tests are missing and I'm not sure about the general structure of your library and what kind of namespaces and directory structure you'd like. So just drop feedback on this if you want.

Just wrote this quickly but it should be already superior to the hardcoded Stockfish class.
I'll eventually write some tests for this unless you do it for me :D

### CODE REVIEW

**Comment by programarivm** [comment]
Thanks for sending this PR, it's very much appreciated! At the moment I'm writing some tests in [this branch](https://github.com/chesslablab/php-chess/tree/generalize-engine-class).

**Comment by Disservin** [comment]
nice ty, push them into this branch once you are ready

**Comment by programarivm** [comment]
Thank you @Disservin, the [docs](http://php-chess.docs.chesslablab.org/play-chess/#play-computer) also have been updated with the new API.

**Comment by Disservin** [comment]
okay but why is this still called stockfish? This is just a normal uci engine and not Stockfish related.

**Comment by Disservin** [comment]
if anything stockfish should inherit from the uciengine, imo. though this is not really required

**Comment by programarivm** [comment]
So these are [the docs](https://php-chess.docs.chesslablab.org/play-chess/#play-computer) for the UciEngine API after the newest update.

```php
use Chess\UciEngine\UciEngine;
use Chess\UciEngine\Details\Limit;
use Chess\Variant\Classical\Board;

$board = new Board();
$board->play('w', 'e4');

$limit = (new Limit())->setDepth(3);
$stockfish = (new UciEngine('/usr/games/stockfish'))->setOption('Skill Level', 9);
$analysis = $stockfish->analyse($board, $limit);

$board->playLan('b', $analysis['bestmove']);

echo $board->getMovetext();
```

The params in Chess\UciEngine\Details\Limit have been updated as per the UCI spec.

**Comment by Disservin** [comment]
Nice looks better already :D 
Tbh I find https://github.com/chesslablab/php-chess/commit/93d7b2fd28f768de8868f10dff824e865a262b11 quite a bit much tbh but that depends on your library style, after all it’s just a plain object to store data, there isn’t really anything to hide or just make it all private and only keep the constructor like python chess https://python-chess.readthedocs.io/en/latest/engine.html#chess.engine.Limit

**Comment by Disservin** [comment]
Also the analysis unit test is a bit useless.. https://github.com/chesslablab/php-chess/blob/main/tests/unit/UciEngine/UciEngineTest.php#L72
this might fail for future versions. Just assert that the move which is returned is a valid move in that position ? Also `UCI_Elo` isnt doing anything unless `UCI_LimitStrength` is turned on.

**Comment by programarivm** [comment]
Yep, it is more of a coding convention than anything else. Also a few more tests are to be added since we've been using a rather basic UciEngine API. It seems as if a new evaluation function should be implemented.

**Pull request closed without merging**
