### PR TITLE
issue/585-PSR-12-compliance-in-Chess-Eval

### LINKED ISSUE #585: PSR-12 compliance in Chess\Eval
Ensure the code in the [Chess\Eval](https://github.com/chesslablab/php-chess/tree/main/src/Eval) namespace is PSR-12 compliant.

### PR DESCRIPTION
**Pull request by TheMarvelFan**
Closes #585 

Most issues were either line-endings related or ' Expected at least 1 space before "." ' in the files.

### CODE REVIEW

**Comment by programarivm** [comment]
Thank you @TheMarvelFan for contributing to this repo!

Let me just point out the following:

- The PR should be named `issue/585-PSR-12-compliance-in-Chess-Eval` as per the convention defined in the Contributing Guidelines.

Keep it up,

**Comment by programarivm** [comment]
The pull request page should inform that 6 commits are to be merged into `chesslablab:main` from `TheMarvelFan:issue/585-PSR-12-compliance-in-Chess-Eval` similarly to the following example:

- https://github.com/chesslablab/php-chess/pull/626

This is how to proceed:

1. Open a new PR with a new (renamed) branch
2. Close the old PR referencing the new one (e.g. Closed in favor of #new_pr_id)

See:

- [Renaming a branch while on pull request](https://stackoverflow.com/questions/20007578/renaming-a-branch-while-on-pull-request)

**Comment by programarivm** [comment]
@TheMarvelFan this example is also okay in terms of naming convention:

- https://github.com/chesslablab/php-chess/pull/622

> 7 commits into `chesslablab:main` from `Neel-07:issue/605-document-chess-eval-centereval-with-comments`

This one was tolerated despite the branch name being inaccurate:

- https://github.com/chesslablab/php-chess/pull/624

> 6 commits into chesslablab:main from TheMarvelFan:custom 

However, on this occasion I think there may be issues if both branches are named `main`:

- https://github.com/chesslablab/php-chess/pull/625

> 6 commits into chesslablab:main from TheMarvelFan:main

Happy coding and learning!

**Comment by TheMarvelFan** [comment]
Alright @programarivm 

I will keep this naming convention in mind for further PRs.

**Comment by TheMarvelFan** [comment]
Closing this PR in favor of PR #627 .

**Comment by programarivm** [comment]
Thanks for the update!

This will make things easier for the repo maintainer to check out the pull request as per [Checking out pull requests locally](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally).

```text
git fetch origin pull/627/head:issue/585-PSR-12-compliance-in-Chess-Eval
Enter passphrase for key '/home/standard/.ssh/id_ed25519': 
remote: Enumerating objects: 12, done.
remote: Counting objects: 100% (12/12), done.
remote: Total 12 (delta 11), reused 12 (delta 11), pack-reused 0 (from 0)
Unpacking objects: 100% (12/12), 1.34 KiB | 124.00 KiB/s, done.
From github.com:chesslablab/php-chess
 * [new ref]           refs/pull/627/head -> issue/585-PSR-12-compliance-in-Chess-Eval
```

Keep it up,

**Pull request closed without merging**
